# cargo-audit configuration
# https://github.com/RustSec/rustsec/blob/main/cargo-audit/audit.toml.example

[advisories]
# Ignore specific advisories
ignore = [
    # paste crate is unmaintained but stable and widely used
    "RUSTSEC-2024-0436",
    # TODO: Upgrade sqlx to 0.8.1+ to fix this vulnerability
    # Binary Protocol Misinterpretation in sqlx 0.7.4
    "RUSTSEC-2024-0363",
]

# Warn on unmaintained crates instead of failing
unmaintained = "warn"
